# Automatically resume from saved position on launch
save-position-on-quit

#Subtitle preferences
sub-pos=106
sub-scale=1.4
slang=en,eng

#Max Volume
volume-max=200

#Open in fullscreen
fs=yes

osc=no
