windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAAAAAAAAAAB38AAAPzAAAAAQAAABkAAAd+AAAENgAAAAACAAAAB4AAAAAAAAAA
    AAAAB38AAAPz
  tabs:
  - active: true
    history:
    - last_visited: '2024-11-02T21:19:58'
      pinned: false
      title: DuckDuckGo — Privacy, simplified.
      url: https://start.duckduckgo.com/
    - last_visited: '2024-11-02T21:20:45'
      pinned: false
      title: yti\ffffFXXXdddd at DuckDuckGo
      url: https://duckduckgo.com/?t=h_&hps=1&start=1&q=yti%5CffffFXXXdddd&ia=web
    - last_visited: '2024-11-02T21:21:05'
      pinned: false
      title: yt at DuckDuckGo
      url: https://duckduckgo.com/?q=yt&t=h_&start=1&ia=web
    - last_visited: '2024-11-02T21:22:10'
      pinned: false
      title: YouTube
      url: https://www.youtube.com/
    - last_visited: '2024-11-02T21:38:30'
      pinned: false
      title: My last video here - YouTube
      url: https://www.youtube.com/watch?v=o7m-vmVejUM
    - active: true
      last_visited: '2024-11-02T21:38:37'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: The horrors of software bugs - YouTube
      url: https://www.youtube.com/watch?v=Iq_r7IcNmUk
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2024-11-02T21:34:00'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'Black Hat Bash: Bash Scripting for Hackers and Pentesters (Bonus: GraphQL
        and Drone hacking) - YouTube'
      url: https://www.youtube.com/watch?v=c1ZCHCwqWls
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2024-11-02T21:34:13'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: The Google Monopoly is Crumbling - YouTube
      url: https://www.youtube.com/watch?v=68R3kwpuLR4
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2024-11-02T21:34:26'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Tecno Spark 30 Pro Review ।। 20k বাজেটের জাতীয় ফোন হতে যাচ্ছে ? - YouTube
      url: https://www.youtube.com/watch?v=Eupyx0z_I6A
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2024-11-02T21:35:21'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: bash scripting - YouTube
      url: https://www.youtube.com/results?search_query=bash+scripting+
      zoom: 1.0
