cursor #e5e1e9
cursor_text_color #c9c5d0

foreground            #e5e1e9
background            #141318
selection_foreground  #312e41
selection_background  #c8c3dc
url_color             #c7bfff

color0   #141318
color1   #ff7292
color2   #7fff98
color3   #ffd972
color4   #b2a9f2
color5   #463f76
color6   #c7bfff
color7   #f1efff
color8   #9a99a5
color9   #ff9fb4
color10  #a5ffb7
color11  #ffe7a5
color12  #cfc8ff
color13  #d7d2ff
color14  #e5e2ff
color15  #f9f8ff
