cursor #dee3e6
cursor_text_color #bfc8cc

foreground            #dee3e6
background            #0f1416
selection_foreground  #1e333b
selection_background  #b3cad4
url_color             #88d1ec

color0   #0f1416
color1   #ff72a0
color2   #76ec82
color3   #fff672
color4   #6ec1e0
color5   #18566d
color6   #88d1ec
color7   #e8f3f7
color8   #8d9699
color9   #ff9fbe
color10  #a5ffaf
color11  #fff9a5
color12  #a3e6ff
color13  #b3eaff
color14  #cef1ff
color15  #f8fdff
