cursor #e5e3d6
cursor_text_color #c8c7b7

foreground            #e5e3d6
background            #13140c
selection_foreground  #30321a
selection_background  #c8c9a6
url_color             #c5cc7a

color0   #13140c
color1   #ea7a69
color2   #71cc66
color3   #ffe972
color4   #b9c164
color5   #585e18
color6   #c5cc7a
color7   #d5d6c9
color8   #83847a
color9   #ffab9f
color10  #a8f49f
color11  #fff1a5
color12  #d9e093
color13  #f8ffb7
color14  #fbffd0
color15  #fefff8
